# Generated by Django 3.2.18 on 2023-06-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esp32', models.CharField(max_length=10)),
                ('mensaje', models.CharField(max_length=250)),
                ('fecha', models.CharField(max_length=15)),
                ('hora', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
